### ISSUE TITLE
Renaming GPIO pins in web UI

### ISSUE THREAD

**Issue by CooperWhitlow** [projectweekend/Pi-GPIO-Server#1]
After adding pins to the config file, they appear with a descriptive title of "{{ p.num }}: {{ p.mode }}" (e.g., 17: LOW). Is there any way to assign custom titles for each panel heading?

**Comment by projectweekend** [comment]
Thanks for opening the issue. There is currently not a way to do this, but I have a couple of ideas for changes. One challenge is that there is no persistence layer for Pi-GPIO-Server, and that was intentional. I didn't want it to require setting up a database, or something like that, if someone wanted to use it. With that said, when editing something from the UI, there is no place to store these edits so that they survive restarts of the server application. 

What if I extended the configuration file format to allow you to give a pin a custom `name` property. You set the name you want in the config file when you initialize the pins. If a `name` is present, that's what will display on the page, else the current behavior would be default. Would this help solve your problem?

**Comment by CooperWhitlow** [comment]
That would be amazing. I don't think it adds unnecessary complexity to the installation of Pi-GPIO-Server, yet still makes implementation/daily use much more user friendly.

**Comment by projectweekend** [comment]
Hey! I just pushed up some changes to allow the optional `name` prop in the config file. README was updated with documentation. Check it out and let me know if there are any issues. Thanks!

**Comment by CooperWhitlow** [comment]
Looks perfect! I'll see how it goes updating this week...

**Comment by CooperWhitlow** [comment]
Thanks so much for sharing this project; It's helped me a lot and works like a charm:
<a href="http://www.youtube.com/watch?feature=player_embedded&v=3EQfkEUouAg" target="_blank"><img src="http://img.youtube.com/vi/3EQfkEUouAg/0.jpg"/></a><br>

--issue closed--

Now I just have to find a <em>simple</em> way to integrate my serial control script for powering on the projectors.

**Comment by projectweekend** [comment]
Rock on! So glad this worked out for you.
